units:
  boots:
  - name: S2iThothF31Py37v01111Vuln0QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-41747 (CVE-2020-1747)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-41747 (CVE-2020-1747) - see 
  - name: S2iThothF31Py37v01111Vuln1QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-45114 (CVE-2021-29923)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-45114 (CVE-2021-29923) - see 
  - name: S2iThothF31Py37v01111Vuln2QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-36333 (CVE-2017-18342)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-36333 (CVE-2017-18342) - see 
  - name: S2iThothF31Py37v01111Vuln3QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-38100 (CVE-2020-1747)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-38100 (CVE-2020-1747) - see 
  - name: S2iThothF31Py37v01111Vuln4QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-39611 (CVE-2020-14343)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-39611 (CVE-2020-14343) - see 
  - name: S2iThothF31Py37v01111Vuln6QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'SNYK-PYTHON-PYYAML-42159' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-PYYAML-42159
      not_acceptable: >-
        The base image used has a CVE SNYK-PYTHON-PYYAML-42159 - see https://snyk.io/vuln/SNYK-PYTHON-PYYAML-42159
  - name: S2iThothF31Py37v01111Vuln7QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'SNYK-PYTHON-PYYAML-590151' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-PYYAML-590151
      not_acceptable: >-
        The base image used has a CVE SNYK-PYTHON-PYYAML-590151 - see https://snyk.io/vuln/SNYK-PYTHON-PYYAML-590151
  - name: S2iThothF31Py37v01111Vuln8QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'SNYK-PYTHON-PYYAML-559098' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-PYYAML-559098
      not_acceptable: >-
        The base image used has a CVE SNYK-PYTHON-PYYAML-559098 - see https://snyk.io/vuln/SNYK-PYTHON-PYYAML-559098
  - name: S2iThothF31Py37v01111Vuln9QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-39525 (CVE-2020-28493)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-39525 (CVE-2020-28493) - see 
  - name: S2iThothF31Py37v01111Vuln10QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'SNYK-PYTHON-JINJA2-1012994' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-JINJA2-1012994
      not_acceptable: >-
        The base image used has a CVE SNYK-PYTHON-JINJA2-1012994 - see https://snyk.io/vuln/SNYK-PYTHON-JINJA2-1012994
  - name: S2iThothF31Py37v01111Vuln11QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-38892 (PVE-2021-38892)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-38892 (PVE-2021-38892) - see 
  - name: S2iThothF31Py37v01111Vuln12QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-39194 (CVE-2020-27783)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-39194 (CVE-2020-27783) - see 
  - name: S2iThothF31Py37v01111Vuln13QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-40072 (CVE-2021-28957)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-40072 (CVE-2021-28957) - see 
  - name: S2iThothF31Py37v01111Vuln16QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-43366 (CVE-2021-43818)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-43366 (CVE-2021-43818) - see 
  - name: S2iThothF31Py37v01111Vuln19QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'SNYK-PYTHON-LXML-1088006' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-LXML-1088006
      not_acceptable: >-
        The base image used has a CVE SNYK-PYTHON-LXML-1088006 - see https://snyk.io/vuln/SNYK-PYTHON-LXML-1088006
  - name: S2iThothF31Py37v01111Vuln20QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'SNYK-PYTHON-LXML-1047473' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-LXML-1047473
      not_acceptable: >-
        The base image used has a CVE SNYK-PYTHON-LXML-1047473 - see https://snyk.io/vuln/SNYK-PYTHON-LXML-1047473
  - name: S2iThothF31Py37v01111Vuln21QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'SNYK-PYTHON-LXML-2316995' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-LXML-2316995
      not_acceptable: >-
        The base image used has a CVE SNYK-PYTHON-LXML-2316995 - see https://snyk.io/vuln/SNYK-PYTHON-LXML-2316995
  - name: S2iThothF31Py37v01111Vuln22QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-38834 (CVE-2020-26137)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-38834 (CVE-2020-26137) - see 
  - name: S2iThothF31Py37v01111Vuln25QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-43975 (CVE-2021-33503)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-43975 (CVE-2021-33503) - see 
  - name: S2iThothF31Py37v01111Vuln26QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'SNYK-PYTHON-URLLIB3-1014645' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-1014645
      not_acceptable: >-
        The base image used has a CVE SNYK-PYTHON-URLLIB3-1014645 - see https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-1014645
  - name: S2iThothF31Py37v01111Vuln27QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'SNYK-PYTHON-URLLIB3-1533435' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-1533435
      not_acceptable: >-
        The base image used has a CVE SNYK-PYTHON-URLLIB3-1533435 - see https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-1533435
  - name: S2iThothF31Py37v01111Vuln28QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-38414 (CVE-2020-13757)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-38414 (CVE-2020-13757) - see 
  - name: S2iThothF31Py37v01111Vuln29QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-38369 (CVE-2020-13757)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-38369 (CVE-2020-13757) - see 
  - name: S2iThothF31Py37v01111Vuln30QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'SNYK-PYTHON-RSA-1038401' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-RSA-1038401
      not_acceptable: >-
        The base image used has a CVE SNYK-PYTHON-RSA-1038401 - see https://snyk.io/vuln/SNYK-PYTHON-RSA-1038401
  - name: S2iThothF31Py37v01111Vuln31QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'SNYK-PYTHON-RSA-570831' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-RSA-570831
      not_acceptable: >-
        The base image used has a CVE SNYK-PYTHON-RSA-570831 - see https://snyk.io/vuln/SNYK-PYTHON-RSA-570831
  - name: S2iThothF31Py37v01111Vuln32QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-38765 (CVE-2019-20916)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-38765 (CVE-2019-20916) - see 
  - name: S2iThothF31Py37v01111Vuln33QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-40291 (CVE-2021-28363)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-40291 (CVE-2021-28363) - see 
  - name: S2iThothF31Py37v01111Vuln34QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-42218 (PVE-2021-42218)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-42218 (PVE-2021-42218) - see 
  - name: S2iThothF31Py37v01111Vuln36QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-42559 (CVE-2021-3572)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-42559 (CVE-2021-3572) - see 
  - name: S2iThothF31Py37v01111Vuln39QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'SNYK-PYTHON-PIP-609855' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-PIP-609855
      not_acceptable: >-
        The base image used has a CVE SNYK-PYTHON-PIP-609855 - see https://snyk.io/vuln/SNYK-PYTHON-PIP-609855
  - name: S2iThothF31Py37v01111Vuln40QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'SNYK-PYTHON-PIP-1278135' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-PIP-1278135
      not_acceptable: >-
        The base image used has a CVE SNYK-PYTHON-PIP-1278135 - see https://snyk.io/vuln/SNYK-PYTHON-PIP-1278135
  - name: S2iThothF31Py37v01111Vuln41QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'SNYK-PYTHON-PYELFTOOLS-1579489' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-PYELFTOOLS-1579489
      not_acceptable: >-
        The base image used has a CVE SNYK-PYTHON-PYELFTOOLS-1579489 - see https://snyk.io/vuln/SNYK-PYTHON-PYELFTOOLS-1579489
  - name: S2iThothF31Py37v01111Vuln42QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-39659 (CVE-2021-21330)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-39659 (CVE-2021-21330) - see 
  - name: S2iThothF31Py37v01111Vuln43QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'pyup.io-42692 (PVE-2021-42692)' in the base image used
        link: 
      not_acceptable: >-
        The base image used has a CVE pyup.io-42692 (PVE-2021-42692) - see 
  - name: S2iThothF31Py37v01111Vuln44QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'SNYK-PYTHON-AIOHTTP-1079232' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-AIOHTTP-1079232
      not_acceptable: >-
        The base image used has a CVE SNYK-PYTHON-AIOHTTP-1079232 - see https://snyk.io/vuln/SNYK-PYTHON-AIOHTTP-1079232
  - name: S2iThothF31Py37v01111Vuln45QuaySecurityErrorBoot
    type: boot
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - security
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: ERROR
        message: >-
          Found vulnerability 'SNYK-PYTHON-AIOHTTP-1584144' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-AIOHTTP-1584144
      not_acceptable: >-
        The base image used has a CVE SNYK-PYTHON-AIOHTTP-1584144 - see https://snyk.io/vuln/SNYK-PYTHON-AIOHTTP-1584144
  wraps:
  - name: S2iThothF31Py37v01111Vuln0QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-41747 (CVE-2020-1747)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln1QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-45114 (CVE-2021-29923)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln2QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-36333 (CVE-2017-18342)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln3QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-38100 (CVE-2020-1747)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln4QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-39611 (CVE-2020-14343)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln6QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'SNYK-PYTHON-PYYAML-42159' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-PYYAML-42159
  - name: S2iThothF31Py37v01111Vuln7QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'SNYK-PYTHON-PYYAML-590151' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-PYYAML-590151
  - name: S2iThothF31Py37v01111Vuln8QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'SNYK-PYTHON-PYYAML-559098' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-PYYAML-559098
  - name: S2iThothF31Py37v01111Vuln9QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-39525 (CVE-2020-28493)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln10QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'SNYK-PYTHON-JINJA2-1012994' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-JINJA2-1012994
  - name: S2iThothF31Py37v01111Vuln11QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-38892 (PVE-2021-38892)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln12QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-39194 (CVE-2020-27783)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln13QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-40072 (CVE-2021-28957)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln16QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-43366 (CVE-2021-43818)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln19QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'SNYK-PYTHON-LXML-1088006' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-LXML-1088006
  - name: S2iThothF31Py37v01111Vuln20QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'SNYK-PYTHON-LXML-1047473' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-LXML-1047473
  - name: S2iThothF31Py37v01111Vuln21QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'SNYK-PYTHON-LXML-2316995' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-LXML-2316995
  - name: S2iThothF31Py37v01111Vuln22QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-38834 (CVE-2020-26137)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln25QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-43975 (CVE-2021-33503)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln26QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'SNYK-PYTHON-URLLIB3-1014645' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-1014645
  - name: S2iThothF31Py37v01111Vuln27QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'SNYK-PYTHON-URLLIB3-1533435' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-1533435
  - name: S2iThothF31Py37v01111Vuln28QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-38414 (CVE-2020-13757)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln29QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-38369 (CVE-2020-13757)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln30QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'SNYK-PYTHON-RSA-1038401' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-RSA-1038401
  - name: S2iThothF31Py37v01111Vuln31QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'SNYK-PYTHON-RSA-570831' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-RSA-570831
  - name: S2iThothF31Py37v01111Vuln32QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-38765 (CVE-2019-20916)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln33QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-40291 (CVE-2021-28363)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln34QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-42218 (PVE-2021-42218)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln36QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-42559 (CVE-2021-3572)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln39QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'SNYK-PYTHON-PIP-609855' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-PIP-609855
  - name: S2iThothF31Py37v01111Vuln40QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'SNYK-PYTHON-PIP-1278135' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-PIP-1278135
  - name: S2iThothF31Py37v01111Vuln41QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'SNYK-PYTHON-PYELFTOOLS-1579489' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-PYELFTOOLS-1579489
  - name: S2iThothF31Py37v01111Vuln42QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-39659 (CVE-2021-21330)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln43QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'pyup.io-42692 (PVE-2021-42692)' in the base image used
        link: 
  - name: S2iThothF31Py37v01111Vuln44QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'SNYK-PYTHON-AIOHTTP-1079232' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-AIOHTTP-1079232
  - name: S2iThothF31Py37v01111Vuln45QuaySecurityWarningWrap
    type: wrap
    should_include:
      adviser_pipeline: true
      recommendation_types:
      - latest
      - performance
      - stable
      - testing
      runtime_environments:
        base_images:
        - quay.io/thoth-station/s2i-thoth-f31-py37:v0.11.11
    run:
      stack_info:
      - type: WARNING
        message: >-
          Found vulnerability 'SNYK-PYTHON-AIOHTTP-1584144' in the base image used
        link: https://snyk.io/vuln/SNYK-PYTHON-AIOHTTP-1584144
